version: '3.3'

services:
  webapp_web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn webapp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/staticfiles/:/webapp/app/staticfiles
      - ./app/mediafiles:/webapp/app/mediafiles

    expose:
      - 8000 
    depends_on:
      - webapp_production_db 
    restart: always 
    environment:  
      - DEBUG=0
      - SECRET_KEY=setsecretkey
      - ALLOWED_HOSTS=localhost
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=webapp_production_db
      - SQL_USER=webapp_production_user
      - SQL_PASSWORD=webapp_production_password
      - SQL_HOST=webapp_production_db
      - SQL_PORT=5432

  webapp_production_db:
    image: postgres:13.0-alpine
    volumes:
      - webapp_production_postgres_data:/var/lib/postgresql/data/  
    environment:
      - POSTGRES_USER=webapp_production_user 
      - POSTGRES_PASSWORD=webapp_production_password
      - POSTGRES_DB=webapp_production_db  
volumes:
  webapp_production_postgres_data: 



