FROM python:3
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /webapp/app
COPY ./requirements.txt .  
RUN pip install -r requirements.txt
COPY . .

ENTRYPOINT ["/webapp/app/entrypoint.sh"]

